version: "3"
services:
  springboot-app:
    container_name: spring-crud
    image: spring-crud-image
    restart: always
    build: .
    ports:
      - 8181:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    depends_on:
      - mysqldb
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: users_database
      MYSQL_ROOT_PASSWORD: root

